version: "3"
services:
  web:
    image: php:7.4-apache
    volumes: 
      - "./:/var/www/html"
    command: >
      sh -c "
      docker-php-ext-install mysqli && \
      docker-php-ext-enable mysqli && \
      apache2-foreground
      "
    ports:
      - 80:80
      - 443:443
    networks:
      - lamp-docker
    links:
        - mariadb:db

  mariadb:
    image: mariadb:10.6.8
    volumes:
      - "/var/lib/mysql/data:/var/lib/mysql"
      - "/var/lib/mysql/logs:/var/lib/mysql"
      - /var/docker/mariadb/conf:/etc/mysql
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: true
        MYSQL_ROOT_PASSWORD: "secret"
        MYSQL_USER: "myuser"
        MYSQL_PASSWORD: "mypass"
        MYSQL_DATABASE: "mydb"
    networks:
      - lamp-docker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - mariadb:db
    ports:
        - 8181:80
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge
